"""empty message

Revision ID: 43c81ca6ed5c
Revises: 7489df97955f
Create Date: 2017-06-19 15:42:52.047812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c81ca6ed5c'
down_revision = '7489df97955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=255), nullable=False),
    sa.Column('os', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'users', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('device_list')
    # ### end Alembic commands ###
