"""empty message

Revision ID: 5d60ab1ffb67
Revises: 
Create Date: 2017-06-14 15:02:43.872503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d60ab1ffb67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backup_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('encrypted_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_key')
    op.drop_column('users', 'backup_key')
    # ### end Alembic commands ###
