"""empty message

Revision ID: 613613961c7a
Revises: 43c81ca6ed5c
Create Date: 2017-06-19 18:38:43.814238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613613961c7a'
down_revision = '43c81ca6ed5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_list', sa.Column('backup_key', sa.String(length=255), nullable=True))
    op.add_column('device_list', sa.Column('encrypted_key', sa.String(length=255), nullable=True))
    op.drop_column('users', 'encrypted_key')
    op.drop_column('users', 'backup_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backup_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('encrypted_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('device_list', 'encrypted_key')
    op.drop_column('device_list', 'backup_key')
    # ### end Alembic commands ###
