"""empty message

Revision ID: 7489df97955f
Revises: 
Create Date: 2017-06-15 11:23:46.304057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7489df97955f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bday', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('job', sa.String(length=255), nullable=True))
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'job')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'country')
    op.drop_column('users', 'biography')
    op.drop_column('users', 'bday')
    # ### end Alembic commands ###
